# Generated by Django 6.0 on 2025-12-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_serilizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_serilizer',
            new_name='Student_ser',
        ),
    ]
